apiVersion: v1
kind: Service
metadata:
  name: transaction-gateway
spec:
  selector:
    app: transaction-gateway
  ports:
    - port: 3001
      targetPort: 3001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  selector:
    app: ledger-service
  ports:
    - port: 3002
      targetPort: 3002
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-worker
spec:
  selector:
    app: analytics-worker
  ports:
    - port: 3003
      targetPort: 3003
      name: http
